// deno-fmt-ignore-file
import {
  ARRAYORDER_BGR,
  ARRAYORDER_RGB,
  BITMAPORDER_1234,
  BITMAPORDER_4321,
  PACKEDLAYOUT_1555,
  PACKEDLAYOUT_2101010,
  PACKEDLAYOUT_332,
  PACKEDLAYOUT_4444,
  PACKEDLAYOUT_5551,
  PACKEDLAYOUT_565,
  PACKEDLAYOUT_8888,
  PACKEDORDER_ABGR,
  PACKEDORDER_ARGB,
  PACKEDORDER_BGRA,
  PACKEDORDER_BGRX,
  PACKEDORDER_RGBA,
  PACKEDORDER_RGBX,
  PACKEDORDER_XBGR,
  PACKEDORDER_XRGB,
  PIXELTYPE_ARRAYU8,
  PIXELTYPE_INDEX1,
  PIXELTYPE_INDEX4,
  PIXELTYPE_INDEX8,
  PIXELTYPE_PACKED16,
  PIXELTYPE_PACKED32,
  PIXELTYPE_PACKED8,
} from "./enums.ts";

function SDL_DEFINE_PIXELFORMAT(
  type: number,
  order: number,
  layout: number,
  bits: number,
  bytes: number,
): number {
  return ((1 << 28) | ((type) << 24) | ((order) << 20) |
    ((layout) << 16) | ((bits) << 8) | ((bytes) << 0));
}

export const PIXELFORMAT_UNKNOWN = 0;
export const PIXELFORMAT_INDEX1LSB = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_INDEX1, BITMAPORDER_4321, 0, 1, 0);
export const PIXELFORMAT_INDEX1MSB = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_INDEX1, BITMAPORDER_1234, 0, 1, 0);
export const PIXELFORMAT_INDEX4LSB = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_INDEX4, BITMAPORDER_4321, 0, 4, 0);
export const PIXELFORMAT_INDEX4MSB = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_INDEX4, BITMAPORDER_1234, 0, 4, 0);
export const PIXELFORMAT_INDEX8 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_INDEX8, 0, 0, 8, 1);
export const PIXELFORMAT_RGB332 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED8, PACKEDORDER_XRGB, PACKEDLAYOUT_332, 8, 1);
export const PIXELFORMAT_XRGB4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XRGB, PACKEDLAYOUT_4444, 12, 2);
export const PIXELFORMAT_RGB444 = PIXELFORMAT_XRGB4444;
export const PIXELFORMAT_XBGR4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XBGR, PACKEDLAYOUT_4444, 12, 2);
export const PIXELFORMAT_BGR444 = PIXELFORMAT_XBGR4444;
export const PIXELFORMAT_XRGB1555 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XRGB, PACKEDLAYOUT_1555, 15, 2);
export const PIXELFORMAT_RGB555 = PIXELFORMAT_XRGB1555;
export const PIXELFORMAT_XBGR1555 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XBGR, PACKEDLAYOUT_1555, 15, 2);
export const PIXELFORMAT_BGR555 = PIXELFORMAT_XBGR1555;
export const PIXELFORMAT_ARGB4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_ARGB, PACKEDLAYOUT_4444, 16, 2);
export const PIXELFORMAT_RGBA4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_RGBA, PACKEDLAYOUT_4444, 16, 2);
export const PIXELFORMAT_ABGR4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_ABGR, PACKEDLAYOUT_4444, 16, 2);
export const PIXELFORMAT_BGRA4444 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_BGRA, PACKEDLAYOUT_4444, 16, 2);
export const PIXELFORMAT_ARGB1555 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_ARGB, PACKEDLAYOUT_1555, 16, 2);
export const PIXELFORMAT_RGBA5551 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_RGBA, PACKEDLAYOUT_5551, 16, 2);
export const PIXELFORMAT_ABGR1555 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_ABGR, PACKEDLAYOUT_1555, 16, 2);
export const PIXELFORMAT_BGRA5551 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_BGRA, PACKEDLAYOUT_5551, 16, 2);
export const PIXELFORMAT_RGB565 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XRGB, PACKEDLAYOUT_565, 16, 2);
export const PIXELFORMAT_BGR565 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED16, PACKEDORDER_XBGR, PACKEDLAYOUT_565, 16, 2);
export const PIXELFORMAT_RGB24 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_ARRAYU8, ARRAYORDER_RGB, 0, 24, 3);
export const PIXELFORMAT_BGR24 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_ARRAYU8, ARRAYORDER_BGR, 0, 24, 3);
export const PIXELFORMAT_XRGB8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_XRGB, PACKEDLAYOUT_8888, 24, 4);
export const PIXELFORMAT_RGB888 = PIXELFORMAT_XRGB8888;
export const PIXELFORMAT_RGBX8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_RGBX, PACKEDLAYOUT_8888, 24, 4);
export const PIXELFORMAT_XBGR8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_XBGR, PACKEDLAYOUT_8888, 24, 4);
export const PIXELFORMAT_BGR888 = PIXELFORMAT_XBGR8888;
export const PIXELFORMAT_BGRX8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_BGRX, PACKEDLAYOUT_8888, 24, 4);
export const PIXELFORMAT_ARGB8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_ARGB, PACKEDLAYOUT_8888, 32, 4);
export const PIXELFORMAT_RGBA8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_RGBA, PACKEDLAYOUT_8888, 32, 4);
export const PIXELFORMAT_ABGR8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_ABGR, PACKEDLAYOUT_8888, 32, 4);
export const PIXELFORMAT_BGRA8888 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_BGRA, PACKEDLAYOUT_8888, 32, 4);
export const PIXELFORMAT_ARGB2101010 = SDL_DEFINE_PIXELFORMAT(PIXELTYPE_PACKED32, PACKEDORDER_ARGB, PACKEDLAYOUT_2101010, 32, 4);
/*
#if SDL_BYTEORDER == SDL_BIG_ENDIAN
  SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_RGBA8888,
  SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_ARGB8888,
  SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_BGRA8888,
  SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_ABGR8888,
#else
  SDL_PIXELFORMAT_RGBA32 = SDL_PIXELFORMAT_ABGR8888,
  SDL_PIXELFORMAT_ARGB32 = SDL_PIXELFORMAT_BGRA8888,
  SDL_PIXELFORMAT_BGRA32 = SDL_PIXELFORMAT_ARGB8888,
  SDL_PIXELFORMAT_ABGR32 = SDL_PIXELFORMAT_RGBA8888,
#endif

  SDL_PIXELFORMAT_YV12 =
      SDL_DEFINE_PIXELFOURCC('Y', 'V', '1', '2'),
  SDL_PIXELFORMAT_IYUV =
      SDL_DEFINE_PIXELFOURCC('I', 'Y', 'U', 'V'),
  SDL_PIXELFORMAT_YUY2 =
      SDL_DEFINE_PIXELFOURCC('Y', 'U', 'Y', '2'),
  SDL_PIXELFORMAT_UYVY =
      SDL_DEFINE_PIXELFOURCC('U', 'Y', 'V', 'Y'),
  SDL_PIXELFORMAT_YVYU =
      SDL_DEFINE_PIXELFOURCC('Y', 'V', 'Y', 'U'),
  SDL_PIXELFORMAT_NV12 =
      SDL_DEFINE_PIXELFOURCC('N', 'V', '1', '2'),
  SDL_PIXELFORMAT_NV21 =
      SDL_DEFINE_PIXELFOURCC('N', 'V', '2', '1'),
  SDL_PIXELFORMAT_EXTERNAL_OES =
      SDL_DEFINE_PIXELFOURCC('O', 'E', 'S', ' ')
*/
